export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS profiles (
    user_id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    display_name TEXT,
    grade TEXT,
    timezone TEXT NOT NULL DEFAULT 'Australia/Sydney',
    onboarding_complete INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS subjects (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    color TEXT,
    icon TEXT,
    priority INTEGER NOT NULL DEFAULT 2 CHECK (priority BETWEEN 1 AND 3),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES profiles(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    subject_id TEXT,
    title TEXT NOT NULL,
    task_type TEXT NOT NULL DEFAULT 'homework' CHECK (task_type IN ('homework', 'assignment', 'exam', 'revision', 'project', 'other')),
    due_at TEXT NOT NULL,
    estimated_minutes INTEGER NOT NULL CHECK (estimated_minutes > 0),
    remaining_minutes INTEGER NOT NULL CHECK (remaining_minutes >= 0),
    priority INTEGER NOT NULL DEFAULT 2 CHECK (priority BETWEEN 1 AND 3),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'archived')),
    notes TEXT NOT NULL DEFAULT '',
    completed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES profiles(user_id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS commitments (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    subject_id TEXT,
    title TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('school', 'sport', 'extracurricular', 'other')),
    start_date TEXT,
    weekday INTEGER CHECK (weekday BETWEEN 0 AND 6),
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    recurrence TEXT NOT NULL DEFAULT 'none' CHECK (recurrence IN ('none', 'weekly', 'weekdays')),
    active INTEGER NOT NULL DEFAULT 1,
    notes TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES profiles(user_id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS user_preferences (
    user_id TEXT PRIMARY KEY,
    bedtime TEXT NOT NULL DEFAULT '22:30',
    wake_time TEXT NOT NULL DEFAULT '06:30',
    minimum_sleep_minutes INTEGER NOT NULL DEFAULT 480 CHECK (minimum_sleep_minutes BETWEEN 360 AND 720),
    max_daily_study_minutes INTEGER NOT NULL DEFAULT 180 CHECK (max_daily_study_minutes BETWEEN 60 AND 480),
    preferred_session_minutes INTEGER NOT NULL DEFAULT 60 CHECK (preferred_session_minutes BETWEEN 25 AND 120),
    break_minutes INTEGER NOT NULL DEFAULT 15 CHECK (break_minutes BETWEEN 5 AND 60),
    updated_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES profiles(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS events (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    source TEXT NOT NULL CHECK (source IN ('arcadia', 'google')),
    external_id TEXT,
    calendar_id TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL CHECK (kind IN ('task', 'study', 'training', 'sleep', 'general')),
    subject TEXT,
    location TEXT,
    start_at TEXT NOT NULL,
    end_at TEXT NOT NULL,
    all_day INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'completed', 'cancelled')),
    editable INTEGER NOT NULL DEFAULT 1,
    recurrence TEXT,
    sync_status TEXT NOT NULL DEFAULT 'local' CHECK (sync_status IN ('local', 'synced', 'pending', 'error')),
    task_id TEXT,
    commitment_id TEXT,
    event_category TEXT NOT NULL DEFAULT 'other' CHECK (event_category IN ('school', 'study', 'sport', 'extracurricular', 'other', 'sleep')),
    outcome TEXT NOT NULL DEFAULT 'planned' CHECK (outcome IN ('planned', 'completed', 'missed')),
    occurrence_key TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL,
    FOREIGN KEY (commitment_id) REFERENCES commitments(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS activity (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    event_id TEXT,
    task_id TEXT,
    outcome TEXT NOT NULL CHECK (outcome IN ('completed', 'missed')),
    duration_minutes INTEGER NOT NULL DEFAULT 0 CHECK (duration_minutes >= 0),
    occurred_at TEXT NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES profiles(user_id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS study_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    event_id TEXT,
    subject TEXT,
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL,
    duration_minutes INTEGER NOT NULL CHECK (duration_minutes >= 0),
    created_at TEXT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS google_connections (
    user_id TEXT PRIMARY KEY,
    encrypted_refresh_token TEXT NOT NULL,
    token_iv TEXT NOT NULL,
    arcadia_calendar_id TEXT,
    connected_at TEXT NOT NULL,
    last_sync_at TEXT,
    FOREIGN KEY (user_id) REFERENCES profiles(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS google_calendars (
    user_id TEXT NOT NULL,
    calendar_id TEXT NOT NULL,
    title TEXT NOT NULL,
    color TEXT,
    access_role TEXT,
    sync_token TEXT,
    selected INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, calendar_id),
    FOREIGN KEY (user_id) REFERENCES google_connections(user_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_states (
    state_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    code_verifier TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS chat_messages (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS proposals (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'applied', 'declined', 'expired')),
    summary TEXT NOT NULL,
    operations_json TEXT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    applied_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_events_user_start ON events(user_id, start_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_events_external ON events(user_id, calendar_id, external_id) WHERE external_id IS NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_events_commitment_occurrence ON events(user_id, commitment_id, occurrence_key) WHERE commitment_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_events_user_task ON events(user_id, task_id, start_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_subjects_user_name ON subjects(user_id, name COLLATE NOCASE)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_user_due ON tasks(user_id, status, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_commitments_user_active ON commitments(user_id, active, recurrence)`,
  `CREATE INDEX IF NOT EXISTS idx_activity_user_occurred ON activity(user_id, occurred_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_activity_event ON activity(user_id, event_id) WHERE event_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_user_started ON study_sessions(user_id, started_at)`,
  `CREATE INDEX IF NOT EXISTS idx_messages_user_created ON chat_messages(user_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_proposals_user_status ON proposals(user_id, status, created_at)`
] as const;
